name: Build and Deploy Pelican

on:
  push:
    branches: [ "source" ]

permissions:
  contents: write

concurrency:
  group: pages-deploy
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install pelican markdown
          fi

      - name: Build Pelican site
        run: |
          if [ -f publishconf.py ]; then
            pelican content -o output -s publishconf.py
          elif [ -f pelicanconf.py ]; then
            pelican content -o output -s pelicanconf.py
          else
            echo "No pelican configuration found (publishconf.py or pelicanconf.py)." >&2
            exit 1
          fi

      - name: Deploy to master (GitHub Pages)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: output
          publish_branch: master
          enable_jekyll: false
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
          force_orphan: true
